'use strict';

angular.module('BlurAdmin', [
  'ngAnimate',
  'ui.bootstrap',
  'ui.sortable',
  'ui.router',
  'ngTouch',
  'toastr',
  'smart-table',
  "xeditable",
  'ui.slimscroll',
  'ngJsTree',
  'angular-progress-button-styles',
  'lbServices',
  // 'Dropbox',
  'BlurAdmin.theme',
  'BlurAdmin.pages',
  'builder',
  'builder.components',
  'validator.rules',
  'gantt',
  'gantt.table',
  'gantt.movable',
  'gantt.tooltips',
  'gantt.progress',
  'gantt.groups',
  'gantt.bounds',
  'gantt.tree',
  'gantt.overlap'
]);